# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Phys. Ocean.
tagline:          'Physical Oceanography'
description:      ''
url:              http://jklymak.github.io/Eos431Phy441/
baseurl:          '/Eos431Phy441'

author:
  name:           'Jody Klymak'
  url:            http://web.uvic.ca/~jklymak

paginate:         5
paginate_path: "blog/page:num"

github:
  repo:           https://github.com/jklymak/Eos431Phy441
